#ifndef DMZMQ_CONFIG_H
#define DMZMQ_CONFIG_H

#include <zmq.h>

#define DMZMQ_API_VERSION "0.1.0"

#define DMZMQ_MAX_SOCKETS 1024
// this should be at least DMZMQ_MAX_SOCKETS*(ceil(log10(DMZMQ_MAX_SOCKETS))+1)
#define DMZMQ_RBUF_SIZE 65536
#define DMZMQ_POLLCACHE_SIZE 8

#define DMZMQ_INT64_SOCKOPTS {ZMQ_AFFINITY, ZMQ_MAXMSGSIZE}
#define DMZMQ_INT64_SOCKOPT_COUNT 2

#define DMZMQ_INT_SOCKOPTS {ZMQ_RECONNECT_IVL_MAX, ZMQ_SNDTIMEO,\
    ZMQ_RCVTIMEO, ZMQ_ROUTER_BEHAVIOR, ZMQ_TCP_KEEPALIVE,\
    ZMQ_TCP_KEEPALIVE_CNT, ZMQ_TCP_KEEPALIVE_IDLE, ZMQ_TCP_KEEPALIVE_INTVL,\
    ZMQ_DELAY_ATTACH_ON_CONNECT, ZMQ_XPUB_VERBOSE, ZMQ_EVENTS, ZMQ_TYPE,\
	ZMQ_IMMEDIATE, ZMQ_IPV6, ZMQ_MECHANISM, ZMQ_PLAIN_SERVER,\
	ZMQ_CURVE_SERVER, ZMQ_PROBE_ROUTER, ZMQ_REQ_RELAXED, ZMQ_REQ_CORRELATE,\
	ZMQ_CONFLATE, ZMQ_ROUTER_HANDOVER, ZMQ_TOS, ZMQ_IPC_FILTER_PID,\
	ZMQ_IPC_FILTER_UID, ZMQ_IPC_FILTER_GID, ZMQ_GSSAPI_SERVER,\
	ZMQ_GSSAPI_PLAINTEXT, ZMQ_HANDSHAKE_IVL, ZMQ_XPUB_NODROP,\
	ZMQ_RATE, ZMQ_RECOVERY_IVL, ZMQ_SNDBUF, ZMQ_RCVBUF, ZMQ_RCVMORE}
#define DMZMQ_INT_SOCKOPT_COUNT 35

#define DMZMQ_STR_SOCKOPTS {ZMQ_IDENTITY, ZMQ_SUBSCRIBE, ZMQ_UNSUBSCRIBE,\
    ZMQ_LAST_ENDPOINT, ZMQ_TCP_ACCEPT_FILTER, ZMQ_PLAIN_USERNAME,\
    ZMQ_PLAIN_PASSWORD, ZMQ_CURVE_PUBLICKEY, ZMQ_CURVE_SECRETKEY,\
    ZMQ_ZAP_DOMAIN, ZMQ_CONNECT_RID, ZMQ_GSSAPI_PRINCIPAL,\
    ZMQ_GSSAPI_SERVICE_PRINCIPAL, ZMQ_SOCKS_PROXY}
#define DMZMQ_STR_SOCKOPT_COUNT 14

#endif//DMZMQ_CONFIG_H
